server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8
#  servlet:
#    context-path: /reed


  #  jpa:
#    hibernate:
#      ddl-auto: create
spring:
  velocity:
    suffix: html
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.101.47.253:3306/yiliao
    username: root
    password: reedfan1991
  redis:
    host: 47.101.47.253
    port: 6379
    password: root
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    #  mybatis主配置文件所在路径
  mapper-locations: classpath:com/reed/ustc/mapper/*.xml  #  所有的mapper映射文件
  type-aliases-package: com.reed.ustc.pojo                  # 定义所有操作类的别名所在包


upload-path: /Users/qufan/Downloads/pictest





